# DepthImageOctomapUpdater is much faster! (~ 20-50 ms vs 60-180ms)

sensors:
  - sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
    image_topic: /camera_right/depth/image_raw
    queue_size: 1
    near_clipping_plane_distance: 0.1
    far_clipping_plane_distance: 1.3
    shadow_threshold: 0.2
    padding_scale: 1.0
    padding_offset: 0.06
    max_update_rate: 0

  - sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
    image_topic: /camera_left/depth/image_raw
    queue_size: 1
    near_clipping_plane_distance: 0.1
    far_clipping_plane_distance: 1.3
    shadow_threshold: 0.2
    padding_scale: 1.0
    padding_offset: 0.06
    max_update_rate: 0

  - sensor_plugin: occupancy_map_monitor/DepthImageOctomapUpdater
    image_topic: /camera_top/depth/image_raw
    queue_size: 1
    near_clipping_plane_distance: 0.1
    far_clipping_plane_distance: 1.0
    shadow_threshold: 0.2
    padding_scale: 1.0
    padding_offset: 0.06
    max_update_rate: 0


# sensors:
#   - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
#     point_cloud_topic: /camera_right/depth/color/points
#     max_range: 1.3
#     point_subsample: 5
#     padding_offset: 0.06
#     padding_scale: 1.0
#     max_update_rate: 0

#   - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
#     point_cloud_topic: /camera_left/depth/color/points
#     max_range: 1.3
#     point_subsample: 5
#     padding_offset: 0.06
#     padding_scale: 1.0
#     max_update_rate: 0

#   - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
#     point_cloud_topic: /camera_top/depth/color/points
#     max_range: 1.0
#     point_subsample: 5
#     padding_offset: 0.06
#     padding_scale: 1.0
#     max_update_rate: 0

