<?xml version="1.0" ?>
<robot name="ur3_workplace" 
  xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find ur3_description)/urdf/ur3.xacro" />

  <xacro:property name="top_wall_z" value="0.75" />
  <xacro:property name="limit_wall_height" value="${top_wall_z + 0.45}" />

  <link name="top_wall">
    <!-- <visual>
      <geometry>
        <box size="0.75 0.9 0.1"/>
      </geometry>
      <material name="black">
        <color rgba="0.2 0.2 0.2 0.2" />
      </material>
    </visual> -->
    <collision>
      <geometry>
        <box size="0.75 0.9 0.1"/>
      </geometry>
    </collision>
  </link>
  <joint name="top_wall_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0.2 0.18 ${top_wall_z}"/>
    <parent link="table"/>
    <child link="top_wall"/>
  </joint>

    <link name="back_wall">
    <!-- <visual>
      <geometry>
        <box size="0.75 0.1 ${limit_wall_height}"/>
      </geometry>
      <material name="black">
        <color rgba="0.2 0.2 0.2 0.2" />
      </material>
    </visual> -->
    <collision>
      <geometry>
         <box size="0.75 0.1 ${limit_wall_height}"/>
      </geometry>
    </collision>
  </link>
  <joint name="back_wall_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0.2 -0.32 0.1"/>
    <parent link="table"/>
    <child link="back_wall"/>
  </joint>


    <link name="left_wall">
    <!-- <visual>
      <geometry>
        <box size="0.1 0.9 ${limit_wall_height}"/>
      </geometry>
      <material name="black">
        <color rgba="0.2 0.2 0.2 0.2" />
      </material>
    </visual> -->
    <collision>
      <geometry>
         <box size="0.1 0.9 ${limit_wall_height}"/>
      </geometry>
    </collision>
  </link>
  <joint name="left_wall_joint" type="fixed">
    <origin rpy="0 0 0" xyz="-0.22 0.18 0.1"/>
    <parent link="table"/>
    <child link="left_wall"/>
  </joint>

</robot>




	
